/**
 * i18n catalog loader + translator.
 * Single source = src/i18n/strings/en.json. Other locales are generated by
 * `npm run i18n:sync` and become indexable after native review (config/locales).
 * Components must read ALL display copy through `t()` — never hard-code strings.
 */
import { DEFAULT_LOCALE } from '../config/locales';

type Catalog = Record<string, string>;

// Eagerly bake every available locale catalog into the build. Supports both
// top-level files (strings/en.json) and per-page namespaces (strings/en/home.json),
// so content + translations can be authored in isolated files and merged here.
const modules = import.meta.glob<{ default: Catalog }>('./strings/**/*.json', { eager: true });

const catalogs: Record<string, Catalog> = {};
for (const path in modules) {
  const rel = path.replace(/^\.\/strings\//, '');
  const parts = rel.split('/');
  const code = parts.length > 1 ? parts[0] : parts[0].replace(/\.json$/, '');
  catalogs[code] = { ...(catalogs[code] ?? {}), ...modules[path].default };
}

const FALLBACK: Catalog = catalogs[DEFAULT_LOCALE] ?? {};

/** Translate `key` for `locale`, interpolating {vars}. Falls back en → key. */
export function t(locale: string, key: string, vars?: Record<string, string | number>): string {
  const c = catalogs[locale] ?? FALLBACK;
  let s = c[key] ?? FALLBACK[key] ?? key;
  if (vars) {
    for (const k in vars) s = s.split('{' + k + '}').join(String(vars[k]));
  }
  return s;
}

/** Returns a `t` bound to one locale — `const tt = useTranslations(locale)`. */
export function useTranslations(locale: string) {
  return (key: string, vars?: Record<string, string | number>) => t(locale, key, vars);
}

/** Split a body string on blank lines into paragraphs. */
export function paragraphs(value: string): string[] {
  return value.split(/\n\s*\n/).map((p) => p.trim()).filter(Boolean);
}

/** True if the locale has its own (non-fallback) value for the key. */
export function hasOwnKey(locale: string, key: string): boolean {
  return Boolean(catalogs[locale] && key in catalogs[locale]);
}

export { catalogs };
